name: "Magic-Tales Helper"
model_type: "openai"
model: "GPT-4o"
temperature: 0.0
instructions_path: "services/openai_assistants/helper_assistant/instructions/helper_assistant_instructions.txt"
story_features_extraction_prompt_path: "services/openai_assistants/helper_assistant/instructions/story_features_extraction_prompt.txt"
synopsis_extraction_prompt_path: "services/openai_assistants/helper_assistant/instructions/synopsis_extraction_prompt.txt"
embedding_type: "openai"
vector_store_type: "chroma"
memory_key: "chat_history"
human_input_key: "human_input"
tools:
  - type: "file_search" 