name: "Magic-Tales Helper"
model: "gpt-4-turbo"
temperature: 0.0
instructions_path: "services/openai_assistants/helper_assistant/instructions/helper_assistant_instructions.txt"
story_features_extraction_prompt_path: "services/openai_assistants/helper_assistant/instructions/story_features_extraction_prompt.txt"
synopsis_extraction_prompt_path: "services/openai_assistants/helper_assistant/instructions/synopsis_extraction_prompt.txt"
tools:
  - type: "file_search"
  - type: "code_interpreter"
