name: "cognitive_agent"
model: "gpt-4-turbo"
temperature: 0.1
instructions_path: "services/openai_assistants/cognitive_agent/instructions/cognitive_agent_instructions.txt"
max_retries: 3
tools:
  - type: "file_search" 
