continue_where_we_left_of: True
chain_of_thoughts_conversations_output_format: "md"
html_files_dark_mode: False
generate_tree_evolution_viz: True
visualize_chapter_generator_response: True
visualize_chapter_critic_response: True