class StoryState:
    USER_FACING_CHAT = "USER_FACING_CHAT"
    STORY_TITLE_GENERATION = "STORY_TITLE_GENERATION"
    STORY_GENERATION = "STORY_GENERATION"
    IMAGE_PROMPT_GENERATION = "IMAGE_PROMPT_GENERATION"
    IMAGE_GENERATION = "IMAGE_GENERATION"
    DOCUMENT_GENERATION = "DOCUMENT_GENERATION"
    FINAL_DOCUMENT_GENERATED = "FINAL_DOCUMENT_GENERATED"
