name: "Magic-Tales Chapter Generator"
model_type: "ollama"
model: "llama3.1"
temperature: 0.0
num_responses: 1
top_p: 0.001  
max_tokens: 600000
max_retries: 2
request_timeout: 240
visualize_image_prompt_generator_response: True