_target_: magic_tales.image_generators.dream_studio.DreamStudioImageGenerator
api_key: ''
host: 'grpc.stability.ai:443'
engine: 'stable-diffusion-xl-1024-v1-0'
steps: 50
config_scale: 8.5
width: 512
height: 512
samples: 1
sampler: 'SAMPLER_K_DPMPP_2M'
save_dir: 'images'
