name: "Smarty Tales"
model_type: "openai"
model: "GPT-4o"
temperature: 0.1
instructions_path: "services/openai_assistants/chat_assistant/instructions/chat_assistant_instructions.txt"
files_path: "services/openai_assistants/chat_assistant/chat_assistant_files"
max_retries: 3
tools:
  - type: "file_search" 
