name: "Smarty Tales"
model: "gpt-4-turbo-2024-04-09"
instructions_path: "services/openai_assistants/chat_assistant/instructions/chat_assistant_instructions.txt"
files_path: "services/openai_assistants/chat_assistant/chat_assistant_files"
max_retries: 3
tools:
  - type: "retrieval"