name: "Smarty Tales"
model: "gpt-4-turbo"
temperature: 0.1
instructions_path: "services/openai_assistants/chat_assistant/instructions/chat_assistant_instructions.txt"
max_retries: 3
tools:
  - type: "file_search"
  - type: "retrieval"
