_target_: magic_tales.turn_based_conversation.synthesizer.eleven_labs_synthesizer.ElevenLabsSynthesizer
config:
  voice_id: "EXAVITQu4vr4xnSDxMaL"
  stability: 0.71
  similarity_boost: 0.5
  style: 0.0
  use_speaker_boost: True  
  default_on: False