defaults:  
  - _self_
  - chapter_scoring: chapter_scoring  
  - image_generator: dalle3 
  - info_extractor: info_extractor
  - main_llm: main_llm
  - mcts: mcts
  - output_artifacts: output_artifacts
  - parser_llm: parser_llm  
  - chat_assistant: chat_assistant  
  - synthesizer: azure_synthesizer
  - database: database
  - embeddings: embeddings  

hydra:
  run:
    dir: .
