defaults:  
  - _self_
  - chat_assistant: chat_assistant  
  - helper_assistant: helper_assistant
  - supervisor_assistant: supervisor_assistant
  - chapter_scoring: chapter_scoring  
  - image_prompt_generator: image_prompt_generator
  - image_generator: dalle3   
  - main_llm: main_llm
  - mcts: mcts
  - output_artifacts: output_artifacts
  - parser_llm: parser_llm    
  - synthesizer: azure_synthesizer
  - database: database  
  - updates_request_prompts: updates_request_prompts

hydra:
  run:
    dir: .
