defaults:  
  - _self_
  - chat_assistant: chat_assistant  
  - helper_assistant: helper_assistant
  - chapter_scoring: chapter_scoring  
  - image_generator: dalle3   
  - main_llm: main_llm
  - mcts: mcts
  - output_artifacts: output_artifacts
  - parser_llm: parser_llm    
  - synthesizer: azure_synthesizer
  - database: database
  - embeddings: embeddings  

hydra:
  run:
    dir: .
