model: "gpt-4-turbo-2024-04-09"
temperature: 0.0
num_responses: 1
max_tokens: 60000
top_p: 0.000
frequency_penalty: 0.0
presence_penalty: 0.0
max_retries: 2
request_timeout: 240
start_cmd: None
end_cmd: None